### ISSUE TITLE
Remote streams & Improper version number?

### ISSUE THREAD

**Issue by daephx** [Hiumee/service.discord.richpresence#1]
Kodi: `v18.7 Leia`
Addon: `v1.2.3`, `v1.2.2`

Tested against the last two release version and Kodi claims they're both still `v1.2.1`.

![kodi_ejL03S7foM](https://user-images.githubusercontent.com/36192863/85196265-ecba8100-b28d-11ea-9f2c-39fa276921bb.png)

It appears as though the addon wont work for my use-case, It seems to hook to discord works initially but when starting a stream from PlexKodiConnect the discord activity shows blank until I completely relaunch kodi. It doesn't seem to work for crunchyroll streams either unfortunately.
So these would be nice additions if you decide it's worth working on.

I have been using this [script](https://github.com/Phineas05/discord-rich-presence-plex) to get similar functionality out of my plex server as a whole but was looking for something that fit into the kodi ecosystem.
I might test it against a fresh install of Kodi when I get the time, keep it up.

**Comment by Hiumee** [comment]
Fixed the version number with the new release.
For media that is streamed using an add-on I can not be sure what data the add-on provides and what not. For now I made it display the text you see in the player. Tested it only with the Twitch add-on and a feedback if it works with others will be great.
I will keep the issue open for your response.

**Comment by Hiumee** [comment]
Added workaround for add-ons that don't set the media fields.

**Comment by daephx** [comment]
Missed the notification, I have updated to `1.2.7` and the version number as well as addons such as crunchyroll and PlexKodiConnect do indeed work on my end. much appreciated!
