### ISSUE TITLE
Wrong Show picture

### ISSUE THREAD

**Issue by zeroquinc** [Hiumee/service.discord.richpresence#11]
I noticed this at least 5 times now, and now I managed to take a screenshot and post an issue about it.
The problem is that whenever I start a show that already ran, so i resume it from for example 24 minutes, the show picture is wrong 9 out of 10 times.

![image](https://github.com/Hiumee/service.discord.richpresence/assets/39315068/4530a910-19f3-4be2-a876-f862c50e2681)

I also saw some random anime sometimes and shows I never seen (mostly foreign) as poster. Do you need logs or can  you look into this? 

I'm on Kodi Nexus with the latest addon version.

Thanks in advance!

**Comment by zeroquinc** [comment]
Also happens now with new started episodes:

![image](https://github.com/Hiumee/service.discord.richpresence/assets/39315068/1a6283cd-eea5-460e-b37d-ddf8b174e445)

**Comment by Hiumee** [comment]
I have logs for the image requests. It appears that the ID sent by your Kodi instalation is a TVDB id, which is not supported by the image endpoint at the moment. It currently accepts TMDB and IMDB. Changing the scraper to TMDB would fix this issue, as Kodi will report the TMDB id. I can't tell why previously it displayed the correct image at the start of the episode.

**Comment by zeroquinc** [comment]
> I have logs for the image requests. It appears that the ID sent by your Kodi instalation is a TVDB id, which is not supported by the image endpoint at the moment. It currently accepts TMDB and IMDB. Changing the scraper to TMDB would fix this issue, as Kodi will report the TMDB id. I can't tell why previously it displayed the correct image at the start of the episode.

Thank you for the quick response. I use Plex via Kodi, and that uses TVDB yeah. I'm not sure if I can change the scraper in Kodi itself. I see that TMDb TV shows is already enabled and thats the only scraper I have active. I will look into this, at least I got a lead now, thanks a lot!

**Comment by Hiumee** [comment]
I can add an option in the settings to disable ID lookup for cases like this and rely on title only. The code for the current image server is here if you are interested in it [Sqare posters](https://github.com/Hiumee/square-posters#sqare-posters)

**Comment by zeroquinc** [comment]
Hmm I don't see a way to change the scraper, it's probably the Plex addon that I use within Kodi. That's a very nice piece of software, the only thing missing is that it would be nice if it could convert a tvdb id to a imdb / tmdb one. I know the Trakt API can do that but I can understand that you don't want another dependency If you could add a way to read on title only we can check out if it works for now!

**Comment by Hiumee** [comment]
There is a new release with the option to disable the ID. Should work for most content with unique names. It is available both in the repository and the release tab. Also, there is no easy way to get the source of the ID to distinguish between TVDB/TMDB/others (IMDB starts with `tt` so it is somewhat possible), as the ID is got using `getIMDBNumber()`, which is not always an IMDB number

**Comment by zeroquinc** [comment]
Thanks mate I noticed the add-on updated and I havent seen a wrong poster since. Appreciated!
