### ISSUE TITLE
Let us change status from playing to watching.

### ISSUE THREAD

**Issue by RealAmethyst** [Hiumee/service.discord.richpresence#12]
Hi. I have a feature request if it's possible to do. I would love to have a way to switch from Playing, to watching. Discord supports playing, watching, listening to, compeating in and a few others for the status thing. Instead of having playing Kodi or playing watching, we could have Watching Kodi, or even better. Watching show or movie title. It would make the status look much cleaner. I hope there is a way to implement this, as it would be really cool. Thanks!

**Comment by Hiumee** [comment]
This is not supported by Discord. Only bot accounts can use `Watching` and other activity types. `Streaming`, `Listening` are special integrations with Twitch and Spotify. If it will be available in the future I will update the addon

**Comment by RealAmethyst** [comment]
Ah ok, thanks for getting back to me on it. I didn't know.
