### ISSUE TITLE
Display Director's Name

### ISSUE THREAD

**Issue by thisanickname** [Hiumee/service.discord.richpresence#14]
I would like to propose an enhancement for the Discord rich presence functionality in Kodi. Specifically, it would be great if the rich presence status could also display the name of the director of the currently playing movie.

Thank you for considering this feature request. I believe it would make a great addition to the already fantastic functionality of the service.discord.richpresence project.

**Comment by Hiumee** [comment]
Added the option to show the directors. You can find it in the settings under "Customize"
