### ISSUE TITLE
New update version 1.7.2 display time issue

### ISSUE THREAD

**Issue by E85Addict** [Hiumee/service.discord.richpresence#15]
The previous version always showed the display time of whatever was playing no problem, it seems that this latest update broke displaying the time in the rich presence it works everywhere else, it auto finds movies/tv with no problem and displays what I'm watching, but the display time is missing.

**Comment by Hiumee** [comment]
This appears to be a Discord bug. I reported it and hopefully will be fixed soon. Only the "Playing" status displays timestamps currently

**Comment by E85Addict** [comment]
Gotcha! that makes sense!

**Comment by E85Addict** [comment]
I was just thinking, many games have an elapsed play time incorporated into their rich presence, maybe it's possible to use the methods they use instead?

**Comment by Hiumee** [comment]
I use the same method and the time is sent. It is just Discord not using the timestamps when the status is anything other than playing. Like watching or listening

**Comment by E85Addict** [comment]
> I use the same method and the time is sent. It is just Discord not using the timestamps when the status is anything other than playing. Like watching or listening

My apologies, I had a brain fart last night, for whatever reason I was thinking it was still "playing" I forgot its now watching, silly me!

**Comment by Hiumee** [comment]
It seems like Discord got an update in the last few days. Setting both the start and end times displays a progress bar now
![image](https://github.com/user-attachments/assets/fd07aaa7-adab-43c1-b41d-19fc90349e59)
