### ISSUE TITLE
Don't crop poster in Discord RPC

### ISSUE THREAD

**Issue by zeroquinc** [Hiumee/service.discord.richpresence#18]
With the new Discord RPC changes, it's not necessary anymore to crop posters because they can be shown in the full length now. Here is an example:

![image](https://github.com/user-attachments/assets/dc6ebf97-1fe3-4bf4-93da-75cd159cc8db)

Would it be possible to stop cropping the posters so Discord shows them in their full size?

**Comment by Hiumee** [comment]
Fixed
