### ISSUE TITLE
Very minor issue regarding pausing

### ISSUE THREAD

**Issue by E85Addict** [Hiumee/service.discord.richpresence#20]
First off let me start by saying all the latest updates and changes have been absolutely amazing, thank you for your hard work! The only issue I've encountered is that when you pause kodi, the display time disappears instead of showing the pause symbol like it use to before. 
![Screenshot 2024-09-30 032804](https://github.com/user-attachments/assets/c52f33ba-14c4-487a-8976-b8318b092953) If you see here this is how it looks with normal playback, no issue at all, it looks great. But when you go to pause it, the display time disappears completely instead of showing the pause icon that it use to show before. 
![Screenshot 2024-09-30 032816](https://github.com/user-attachments/assets/f83302a0-1075-46b0-bf3e-d0e21bd56263)

**Comment by Hiumee** [comment]
Fixed. Forgot to upload the pause asset for the "TV" and "Movies". Might take a bit for discord's caching to catch up

**Comment by E85Addict** [comment]
> Fixed. Forgot to upload the pause asset for the "TV" and "Movies". Might take a bit for discord's caching to catch up

Seems to be working! My only question is, is it not possible to keep the timestamp when paused as well on exact time it was paused on?
![image](https://github.com/user-attachments/assets/7c7af019-79cc-41b1-88c2-f3af756383f4)
![image](https://github.com/user-attachments/assets/75767558-f6a2-4ef7-9505-cba9dae08cfc)

**Comment by Hiumee** [comment]
As far as I know, no. I just set the start and end dates. Discord does the rest. I can update every second to keep the timestamp in place but other people will keep seeing the same 15 seconds looping - this is the maximum refresh rate for the presence

**Comment by E85Addict** [comment]
Ahh gotcha, no worries then!
