### ISSUE TITLE
Image updating

### ISSUE THREAD

**Issue by auravoid** [Hiumee/service.discord.richpresence#3]
Having the "image updating depending on media" might not be a thing you can do. The images would all have to be cached on Discord to be able to do something like that. It would be really nice to have a feature like this, but I don't think it'll be a possibility for a while. 

Even still, this is an amazing resource and should definitely be added to the official Kodi addon repo.

**Comment by Hiumee** [comment]
I am aware of this issue. I am hopeful Discord will change some thing to make this possible. The work for this feature is mostly done if it will be possible in the future.
