### ISSUE TITLE
I have a an error when installing now

### ISSUE THREAD

**Issue by P3a-nut** [Hiumee/service.discord.richpresence#5]
it says "The dependency on xbmc.python version 2.25.0 could not be satisfied"

**Comment by Hiumee** [comment]
Without more information about your setup I can't narrow down the problem. Please include data about what version of Kodi do you use, and a debug log.
Using a newer version of Kodi might help. Both the repository and the addon were tested on 18.8 (python2) and 19.0 (python3).

**Comment by P3a-nut** [comment]
I'm using 19.0.

**Comment by Hiumee** [comment]
The repository (from README) should download the right version. The versions from the release section are for 18.0-18.8.
If you want to download only the addon you can go in the matrix folder at [https://github.com/Hiumee/kodi-repository](https://github.com/Hiumee/kodi-repository) and download the zip

**Comment by P3a-nut** [comment]
Downloading it separately worked, Thank you.
